"""Refit with Fan Interest — the primary OOTP demand driver.
Uses current-season avg attendance/game (partial season, but per-game is comparable)."""
import numpy as np

# MLB teams only, this season
# (team, market, loyalty, price, avg_att_per_game, fan_interest)
rows = [
    ("OAK", "Big",          "Great",     49.69, 32554, 100),
    ("NYM", "Big",          "Good",      33.00, 40975, 100),
    ("STL", "Big",          "Good",      42.00, 33057,  99),
    ("TEX", "Big",          "Very Good", 38.25, 40936,  93),
    ("NYY", "Astronomical", "Good",      39.54, 35952,  91),
    ("MIN", "Very Big",     "Above Avg", 32.50, 42770,  88),
    ("WAS", "Big",          "Very Good", 41.75, 40788,  88),
    ("CHC", "Very Big",     "Great",     37.00, 36789,  87),
    ("HOU", "Big",          "Extreme",   55.00, 28508,  87),
    ("MON", "Big",          "Very Good", 42.50, 28302,  87),
    ("PIT", "Big",          "Good",      41.42, 29650,  85),
    ("ARI", "Big",          "Good",      37.11, 38195,  84),
    ("CLE", "Big",          "Very Good", 36.00, 34033,  81),
    ("ANA", "Big",          "Above Avg", 41.00, 34238,  80),
    ("PHI", "Huge",         "Good",      41.00, 26876,  80),
    ("KCM", "Very Big",     "Very Good", 41.00, 34076,  79),
    ("LAD", "Big",          "Great",     34.20, 38306,  79),
    ("BAL", "Very Big",     "Very Good", 35.55, 31760,  75),
    ("COL", "Big",          "Good",      40.00, 25654,  73),
    ("DET", "Big",          "Above Avg", 37.00, 27101,  72),
    ("BOS", "Big",          "Good",      37.00, 25318,  69),
    ("TOR", "Very Big",     "Above Avg", 38.50, 24894,  68),
    ("SF",  "Big",          "Below Avg", 29.36, 31321,  68),
    ("MIL", "Big",          "Good",      35.00, 28753,  68),
    ("CWS", "Big",          "Good",      36.36, 28524,  66),
    ("ATL", "Above Avg",    "Above Avg", 35.00, 27046,  61),
    ("SEA", "Very Big",     "Good",      30.13, 25119,  61),
    ("CIN", "Very Big",     "Above Avg", 27.50, 27564,  59),
    ("SD",  "Big",          "Above Avg", 35.06, 24216,  58),
    ("KCR", "Big",          "Good",      32.50, 27089,  56),
    ("TB",  "Big",          "Above Avg", 30.00, 21840,  52),
    ("FLA", "Big",          "Average",   30.00, 22218,  52),
]

market_score = {"Above Avg": 5, "Big": 6, "Very Big": 7, "Huge": 8, "Astronomical": 10}
loyalty_score = {"Below Avg": 2, "Average": 3, "Above Avg": 5, "Good": 6, "Very Good": 7, "Great": 8, "Extreme": 10}

teams  = [r[0] for r in rows]
market = np.array([market_score[r[1]] for r in rows], dtype=float)
loyal  = np.array([loyalty_score[r[2]] for r in rows], dtype=float)
price  = np.array([r[3] for r in rows], dtype=float)
att    = np.array([r[4] for r in rows], dtype=float)
fi     = np.array([r[5] for r in rows], dtype=float)
cap    = 45000.0

# Drop teams at/above 90% capacity — attendance is censored by stadium size
pct_full = att / cap
uncensored = pct_full < 0.88
print(f"Fitting on {uncensored.sum()} of {len(rows)} teams (dropped {(~uncensored).sum()} capacity-constrained)")
print("Dropped:", [f"{teams[i]}({pct_full[i]*100:.0f}%)" for i in range(len(rows)) if not uncensored[i]])

y = np.log(att[uncensored])
X = np.column_stack([
    np.ones(uncensored.sum()),
    fi[uncensored],
    market[uncensored],
    loyal[uncensored],
    np.log(price[uncensored]),
])

beta, *_ = np.linalg.lstsq(X, y, rcond=None)
b0, b_fi, b_m, b_l, b_p = beta
print(f"\nCoefficients:")
print(f"  intercept     = {b0:.4f}")
print(f"  fan interest  = {b_fi:.5f}   (+10 FI -> +{(np.exp(b_fi*10)-1)*100:.1f}% att)")
print(f"  market score  = {b_m:.4f}    (+1 tier   -> +{(np.exp(b_m)-1)*100:.1f}% att)")
print(f"  loyalty score = {b_l:.4f}    (+1 tier   -> +{(np.exp(b_l)-1)*100:.1f}% att)")
print(f"  ln(price)     = {b_p:.4f}    (price elasticity)")

yhat = X @ beta
ss_res = ((y - yhat) ** 2).sum()
ss_tot = ((y - y.mean()) ** 2).sum()
print(f"  R^2           = {1 - ss_res/ss_tot:.3f}")

# Full-sample predictions (uncapped then capped)
Xall = np.column_stack([np.ones_like(fi), fi, market, loyal, np.log(price)])
pred = np.exp(Xall @ beta)
print("\nTeam      FI  price  actual   predicted   diff%   %full")
for i, t in enumerate(teams):
    diff = (pred[i] - att[i]) / att[i] * 100
    print(f"  {t:4s} {fi[i]:3.0f}  ${price[i]:5.2f}  {att[i]:6,.0f}  {pred[i]:10,.0f}  {diff:+6.1f}%  {pct_full[i]*100:4.0f}%")

# Save coefficients for the web app
with open("ticket_model_coefs.js", "w") as f:
    f.write(f"""// Auto-generated by ticket_model_fit_v2.py
// Log-log demand: ln(avg_att) = b0 + b_fi*FI + b_m*market + b_l*loyalty + b_p*ln(price)
// Fit on {uncensored.sum()} MLB teams (dropped {(~uncensored).sum()} capacity-constrained)
// R^2 = {1 - ss_res/ss_tot:.3f}
export const MODEL = {{
  intercept: {b0:.6f},
  fanInterest: {b_fi:.6f},
  market: {b_m:.6f},
  loyalty: {b_l:.6f},
  lnPrice: {b_p:.6f},
}};
""")
print("\nWrote ticket_model_coefs.js")
