// Auto-generated by ticket_model_fit_v2.py
// Log-log demand: ln(avg_att) = b0 + b_fi*FI + b_m*market + b_l*loyalty + b_p*ln(price)
// Fit on 28 MLB teams (dropped 4 capacity-constrained)
// R^2 = 0.704
export const MODEL = {
  intercept: 11.940948,
  fanInterest: 0.013993,
  market: -0.008690,
  loyalty: 0.022660,
  lnPrice: -0.768989,
};
